version: '3.1'

services:
  pg:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    command: -p ${DB_PORT}
  soaker:
    build:
      dockerfile: "Dockerfile.soaker"
    ports:
      - ${SOAKER_PORT}:${SOAKER_PORT}
    expose:
      - ${SOAKER_PORT}
    environment:
      SOAKER_PORT: ${SOAKER_PORT}
